language: go
go:
  - 1.7.1

# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments

before_script:
  - go get -u -v github.com/spf13/hugo

# Clean and don't fail
install:
  - rm -rf public || exit 0

# Build the website
script:
  - yarn --cwd themes/gallery build
  - hugo --theme=gallery

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
