baseURL = "https://daiyi.co/portfolio"
title = "daiyi"
# for smart copyright line, leave this blank and check [params.copyright]
# copyright = ""
theme = "gallery"

Paginate = 15
preserveTaxonomyNames = true
enableEmoji = true
pygmentsCodefences = true         # Syntax Highlighting ( https://gohugo.io/content-management/syntax-highlighting/ )
enableRobotsTXT = true            # generate robots.txt
defaultContentLanguage = "en"     # Missing translations will default to this content language

[params.info]
description = "drawings & projects"
title404 = "not a real page"

[params.assets]
favicon = "images/dinorider.gif"
customCSS = ["css/custom.css"]
customJS = ["js/custom.js"]
gopher = "" # used in 404 template ( Generator: https://gopherize.me )

# [params.copyright]
# prefix = ""
# holder = "daiyi"
# startYear = "2017"
# suffix = ""

[params.settings]
# date & time format: https://golang.org/pkg/time/
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
archiveDateFormat = "Jan 02"
hideEntryNavigation = ["page"] # boolean / array of sections
hideEntryMeta = ["page"] # boolean / array of sections
showReadingTime = true
showLastmod = true
taxonomyCloudShuffle = true
accentColor = "#16e4d2"
hideMainMenu = false

[params.sidebar]
enable = true

[params.widgets]
homepage = []
sidebar = ["about","sidebar_menu", "social_menu"]
footer = []

[params.opengraph.twitter]
page = "daiyitastic"

[params.seo]
# Title Separator: - – — · • * ⋆ | ~ « » < >
titleSeparator = "•"

[params.social]
email = "art@daiyi.co"
github = "daiyi"
instagram = "daiyitastic"
twitter = "daiyitastic"

[params.comments]
enable = false

# Isso: https://posativ.org/isso/
[params.comments.isso]
enable = false
scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

[taxonomies]
author = "authors"
category = "categories"
series = "series"
tag = "tags"

[permalinks]
page = "/:slug/"

# [[menu.main]]
# name = "about"
# weight = -10
# identifier = "about"
# url = "https://daiyi.co"

[languages]
# edit this block for your own language
[languages.en]
lang = "en"
languageName = "English"
weight = 1
